---
- name: Configure server for Siren Platform
  hosts: elasticservers
  become: yes

  tasks:
    - name: Set node_role variable based on hostname
      set_fact:
        node_role: "{{ 'MASTER' if 'master' in hostname else 'DATA' }}"
      vars:
        hostname: "{{ ansible_hostname }}"  # Getting the hostname of the current host
      run_once: true  # This task runs only once on the controller node

  vars:
    siren_download_url: "https://download.siren.io/platform/download/?component=siren-platform-no-data-with-security&os=linux&versio>    siren_zip_name: "siren-platform.zip"
    siren_folder_name: "siren-platform"
    cluster_name: "ElasticSiren-Cluster-With-Security"
    master_nodes: "master-1"  # Comma-separated list of master nodes
    seed_hosts: 192.168.XX.XXY, 192.168.XX.XYZ  # Comma-separated list of seed hosts

  roles:
    - common