---
# roles/common/tasks/permissions/set_permissions.yml

- name: Ensure users have write permissions on /opt
  ansible.builtin.file:
    path: /opt
    state: directory
    mode: '1777'
  become: yes
  become_user: root