---
# roles/common/tasks/users/set_passwords.yml

- name: Set password for elastic user
  ansible.builtin.shell:
    cmd: echo 'elastic:root' | chpasswd
  become: yes

- name: Set password for siren user
  ansible.builtin.shell:
    cmd: echo 'siren:root' | chpasswd
  become: yes